### ISSUE TITLE
Invalid date thrown when clicking on the month

### ISSUE THREAD

**Issue by gwesio** [bendavis78/paper-date-picker#1]
Hello,
First, kudos for implementing the widget - it's really missing from polymer elements. I am looking into using this widget and have noticed few small issues so I thought I'd let you know.

I have noticed, when I try to tap on the name of the month inside core list ```selectedDateChanged``` function gets triggered but the date is invalid and this.value becomes NaN which then escalates to other components and results in errors and 'Inavalid Date' on the left hand side of the widget.
Looking at the structure I would expect ```scrollToMonth``` to fire first when I tap on say 'April 2015' but it's the selectedDateChanged that hits the breakpoint.

**Comment by gwesio** [comment]
also I have noticed you are trying to call scrollToMonth with on-press, should this not be replaced with on-tap instead? It seems like scrollToMonth is not triggered at all currently.

**Comment by bendavis78** [comment]
This appears to have been fixed in both v0.1 and v1.0 branches.
