### ISSUE TITLE
Update to latest dependencies

### ISSUE THREAD

**Issue by nocquidant** [bendavis78/paper-date-picker#109]
Thank you for your component, it's very nice.

But could you please update dependencies to latest versions? Below is what I get in my Chrome console when I import element paper-date-picker.html:

```
iron-shadow-flex-layout.html:12 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
iron-flex-layout.html:14 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
iron-fit-behavior.html:221 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

Thanks again,
--nick

**Comment by osolano** [comment]
I would also like to upvote this fix. I'm getting the same errors.

**Comment by bendavis78** [comment]
I'm not seeing these errors in the demo after testing today. Can you confirm this issue still exists in your setup with latest `iron-flex-layout`?

**Comment by nocquidant** [comment]
I must say that I had to change for another component as i had issues on IE (navigation didn't work well).

**Comment by web-padawan** [comment]
@nocquidant would you report about your IE issues a bit more so we could look into them?

@bendavis78 you're right, those errors have gone away.

**Comment by nocquidant** [comment]
Go to the official paper-date-picker demo page and click next/previous month in a "compulsive way": sometimes it blocks (same behavior on IE/FF/Edge).

**Comment by bendavis78** [comment]
I'm not sure what you mean by clicking next/prev in a "compulsive way". You mean just "really fast"? If so, any blocking is normal and expected as a limit of browser speed.
