### ISSUE TITLE
Not working in Safari/Firefox

### ISSUE THREAD

**Issue by remarkable-ky** [bendavis78/paper-date-picker#11]
Below errors are from Safari

[Warning] Invalid CSS property declaration at: @apply (index.html, line 21)
[Warning] Invalid CSS property declaration at: @apply (index.html, line 28)
[Error] TypeError: undefined is not an object (evaluating 'scope.$.picker')
	(anonymous function)
[Warning] [dom-bind::_createEventHandler]: – "listener method `showDialog` not defined"

**Comment by bendavis78** [comment]
The demo should now be working in FireFox.
