### ISSUE TITLE
max-date enables switch to blank future month

### ISSUE THREAD

**Issue by IftachSadeh** [bendavis78/paper-date-picker#114]
When setting `max-date` , pressing the icon to switch to the next month causes a transition to a blank month-view. In the following example - a blank view of June:
```html
<!DOCTYPE html>
<html>
  <head>
    <base href="http://bendavis78.github.io/paper-date-picker/">
    <script type="text/javascript" src="webcomponentsjs/webcomponents.js"></script>
  </head>
  <body>
    <link rel="import" href="polymer/polymer.html">
    <link rel="import" href="paper-styles/demo-pages.html">
    <link rel="import" href="paper-date-picker/paper-date-picker.html">
 
    <template is="dom-bind">
      <paper-date-picker force-narrow max-date="2016-05-20"> </paper-date-picker>
    </template>
  </body>
</html>
```
After pressing on the button on the top-left to go one month back from the blank view, we end up, not back in May, but in April.

We also have the unexpected behavior, where in this example, if today is "2016-05-29", then this date is selected by default, even though it is within the excluded range.

**Comment by dgabrielli76** [comment]
Effectively you’re right I have been confronted to this issue too.
To add a small exemple you can follow [this plunker](http://plnkr.co/edit/lpa69rRse2YuhXetbOsH?p=preview)

In this plunker the max-date has been set to the 29th June 2016, and if you continue to swipe after June, you arrive on a blank page.

I am already working on a fix, I will propose a PR soon to fix this issue.

**Comment by josemsantos** [comment]
Hello,
Any news about this issue? Will be the PR merged?
Cheers
