### ISSUE TITLE
Feature request - switch view back to selected

### ISSUE THREAD

**Issue by IftachSadeh** [bendavis78/paper-date-picker#115]
It would be really nice, if there was the either or both of following behaviors -
- If a user taps the day heading (e.g., `Sun, May 15`) and we are in another month (not May), then the view switches to May.
- There was a `Selected` button option, where the user could tap to bring the view back to the selected month (in this case May).

**Comment by bendavis78** [comment]
I like the idea of tapping the month/day header bringing us back to the selected month.  An extra button would add UI clutter. 

Pull requests welcome!

**Comment by bendavis78** [comment]
Added in 1.1.5
