### ISSUE TITLE
Feature request - change event listener

### ISSUE THREAD

**Issue by IftachSadeh** [bendavis78/paper-date-picker#117]
It would be very handy to have the possibility to set up an event listener on any change by the user (e.g., a selection of a new year or date).

**Comment by bendavis78** [comment]
Not sure what you mean. Polymer's data binding system means that you can listen to any change. Can you provide a use case as an example?

**Comment by ibarrick** [comment]
Also would like this as I plan on wrapping it in an Ember component and 2 way binding doesn't work between Polymer and Ember.

**Comment by admwx7** [comment]
You can treat this element like an HTML native element and use `addEventListener` just like you would for any other element, Polymer handles the internals of firing our `on-<prop>-changed` events for us so you can complete your bindings however you want.
