### ISSUE TITLE
Monday as first day of the week

### ISSUE THREAD

**Issue by avizcaino-newuibcn** [bendavis78/paper-date-picker#119]
Hi,

is there a way to change the first day of the week to monday? I found that this was solved in 1.1.0 but couldn't find how it is done nor the documentation is updated (if this can be achieved by configuration).

Thanks!

**Comment by bendavis78** [comment]
The first day of the week is set automatically based on locale.

**Comment by avizcaino** [comment]
Hi @bendavis78, I'm having the same problem.

I have my moment locale set to another language (catalan) and it is not working either...

I had to override the locale with this and it works for me:
```
    this._datePicker = (<HTMLElement>this._element).querySelector('paper-date-picker');
    this._datePicker.locale = 'ca'
```

Where is the locale (set to english by default) changed? I couldn't find it in the component.

Thanks!
