### ISSUE TITLE
Show only Day name

### ISSUE THREAD

**Issue by rokity** [bendavis78/paper-date-picker#131]
Hi 
I want to show only the day's name , can I do it ?
Like this picture. 
![14075162_10209151283531911_1003978339_o](https://cloud.githubusercontent.com/assets/6599179/18141538/2a1897be-6fba-11e6-9157-1a723639d518.jpg)

**Comment by bendavis78** [comment]
This falls outside the scope of intended use. You could possibly override CSS variables used in `paper-date-picker.html` and use `display:none` to hide the parts you don't want.

**Comment by rokity** [comment]
Thank you.
