### ISSUE TITLE
Feature Request: Implement iron-selectable-behavior 

### ISSUE THREAD

**Issue by TecHunter** [bendavis78/paper-date-picker#132]
Hi,

It would be nice to implement the behavior so that we can integrate this in a paper-dropdown-menu for example.

What do you think?

**Comment by admwx7** [comment]
Not sure how this would play out since it would become a dropdown that when clicked generates a modal overlay to select a date?  If you just want a dropdown to select a date that's easy enough to implement and there's another issue already out for creating a pre-built dropdown implementation.
