### ISSUE TITLE
When specifying maxDate as a value which is in next year than the current selection the navigation for date doesn't work

### ISSUE THREAD

**Issue by lahsivjar** [bendavis78/paper-date-picker#133]
I found a bug when specifying a maxDate as a value which is in next year than the current selection for example: 
<code>&lt;paper-date-picker date="September 09, 2016" min-date="September 09, 2016" max-date="March 12, 2017"&gt;&lt;/paper-date-picker&gt;</code>

In such case nothing happens when you try to navigate to another year. The problem comes from line number: https://github.com/bendavis78/paper-date-picker/blame/master/paper-calendar.html#L526

The reason is that the if condition in this line is not correct. Adding another OR should solve the issue:

<code>if (!this.maxDate || this.currentYear < this.maxDate.getFullYear() || this.currentMonth < this.maxDate.getMonth() + 1) {</code>

**Comment by lahsivjar** [comment]
FYI, I failed to generate the issue in plunker (http://plnkr.co/edit/9c787GHiBzX7zI5x6gsX) since the code used there seems to be old and doesn't have the problem.

**Comment by julie2013** [comment]
I met the same problem, and your code can fix this problem.

**Comment by Mipme** [comment]
thx for the fix, works perfectly (paper-date-picker 1.2.0)
