### ISSUE TITLE
Duplicate moment import

### ISSUE THREAD

**Issue by web-padawan** [bendavis78/paper-date-picker#134]
both [moment-import](https://github.com/bendavis78/paper-date-picker/blob/master/paper-calendar.html#L10) and [moment-with-locales-import](https://github.com/bendavis78/paper-date-picker/blob/master/paper-date-picker.html#L14) are loaded now 👎 

Will create a PR to fix that.

**Comment by whenlit** [comment]
+1. The default locales can now only be loaded by adding _another_ script tag.
