### ISSUE TITLE
locale does nothing? 

### ISSUE THREAD

**Issue by julie2013** [bendavis78/paper-date-picker#141]
I use paper-date-picker(v1.2), and set locale like this:
`<paper-date-picker locale="fr"></paper-date-picker>`.

But the locale setting doesn't work, still display in English.  How to use locale?

**Comment by web-padawan** [comment]
Since 1.2, you must load moment locales yourself (previously, the whole full bundle was used).

**Comment by SylvainAssemat** [comment]
Meaning add :
<script src="./bower_components/moment/min/locales.js"></script>

Thanks **web-padawan** (help me twice today 👍 👍 )
