### ISSUE TITLE
Why maxDate does not work as expected?

### ISSUE THREAD

**Issue by julie2013** [bendavis78/paper-date-picker#142]
I set maxDate as the following: 
`<paper-date-picker min-date="Apr 01, 2015" max-date="Oct 19, 2017" date="Sep 20, 2016"></paper-date-picker>`,

When I click ">", it only navigates to Oct 2016,  and stuck there.  I could not navigate to next month after Oct 2016.  Also when I click "<" to navigate to previous month until Apr 2015,  then click ">",  the window is stuck on Oct 2015. I also can not navigate to next month after Oct, 2015.

I use Chrome(52.0.2743.116), paper-date-picker(v1.2). 

How did this happen?

**Comment by julie2013** [comment]
It looks code in #133 can fix this problem.

**Comment by bendavis78** [comment]
Fixed in 86ecebc
