### ISSUE TITLE
Error when use maxDate:  Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by julie2013** [bendavis78/paper-date-picker#144]
Here is the steps to reproduce: 
`<paper-date-picker min-date="August 10, 2016" max-date="January 13, 2019" date="Sep 20, 2016"></paper-date-picker>`

Click the year number from calendar and choose "2019" from year list,  the  new date will be "Sep 20 2019".  The console will continue to output warning messages "Date outside of valid range: " (paper-calendar.html line 628).  After thousands of warnings,  a new error "Uncaught exception" will output ,  later another error "Uncaught RangeError: Maximum call stack size exceeded.".

This problem is coming from https://github.com/bendavis78/paper-date-picker/blame/master/paper-calendar.html#L629.

**Comment by bendavis78** [comment]
Fixed in 86ecebc
