### ISSUE TITLE
Error when use minDate: Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by julie2013** [bendavis78/paper-date-picker#146]
Similar to #144.
`<paper-date-picker min-date="Dec 12, 2015" max-date="Aug 10, 2017" date="Sep 20, 2016"></paper-date-picker>`

Click the year number from calendar and choose "2015" from year list, the new date will be "Sep 20, 2015". The console will continue to output warning messages "Date outside of valid range: " (paper-calendar.html line 628). After thousands of warnings, a new error "Uncaught exception" will output , later another error "Uncaught RangeError: Maximum call stack size exceeded.".

This problem is coming from https://github.com/bendavis78/paper-date-picker/blame/master/paper-calendar.html#L629.

**Comment by bendavis78** [comment]
Fixed in 86ecebc
