### ISSUE TITLE
Component page is empty

### ISSUE THREAD

**Issue by nojaf** [bendavis78/paper-date-picker#15]
Hi, looks like the readme is pointing to an empty page.
See <a href="http://bendavis78.github.io/paper-date-picker/" target="_blank">http://bendavis78.github.io/paper-date-picker/</a>

**Comment by devinivy** [comment]
True!  I'm cloning to check-out the demo.

**Comment by Link2Twenty** [comment]
http://bendavis78.github.io/paper-date-picker/paper-date-picker/ this is the actual link for it.

**Comment by bendavis78** [comment]
Thanks! I realized the index.html redirect wasn't working. Should be fixed now.
