### ISSUE TITLE
Not showing the years and months.

### ISSUE THREAD

**Issue by Manohar-Gunturu** [bendavis78/paper-date-picker#166]
While working with paper-date-picker, I noticed that if a user tried to change the year it's showing blank calendar. And the error that I seen in the console was.

`Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing   `

**Comment by Manohar-Gunturu** [comment]
When I click on the year it is not showing the list of years as shown below.
![vcv](https://cloud.githubusercontent.com/assets/6416138/21149256/f173053e-c180-11e6-8cd9-6897b85eb54e.PNG)

I faced this problem at http://bendavis78.github.io/paper-date-picker/paper-date-picker/

**Comment by Link2Twenty** [comment]
Which browser were you using? I was unable to recreate the problem in firefox or chrome.

**Comment by admwx7** [comment]
Since there was no response for additional information and I'm unable to recreate it as all was @Link2Twenty I'm going to close this issue out, if someone else notices the issue please re-open or create a new ticket with affected browers and any screenshots you think would be relevant then tag me.
