### ISSUE TITLE
Reloading moment.js breaks other components

### ISSUE THREAD

**Issue by fairsayan** [bendavis78/paper-date-picker#171]
Hi,
in my app I load momentjs in my index.html:
```javascript
    <script src="../bower_components/moment/min/moment-with-locales.min.js"></script>
    <script src="../bower_components/moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js"></script>
```
because I need it in different pages.
In one of them I use paper-date-picker, but after this page is loaded, the constructor `moment.tz` and all the others functions related with moment-timezone are undefined.
I dug into this issue and I discovered that you call moment-element to provide another version of moment (without timezone).
I commented the loading stuff in moment-element and now everything works fine.

I tried to put my <script> to load moment-timezone inside each component that uses it, but it works only for the first time I visit the component and after, if I load paper-date-picker and I go back to my component, I will obtain moment.tz is undefined because moment-element will have overwritten the moment object without moment.tz and the browser won't load my moment version again since my component is already loaded.

So what? My suggestion is to get riddle of moment-element and ask in the document to load in advance a proper version of momentjs instead of trying to manage all the possible different versions of momentjs.

**Comment by admwx7** [comment]
You want to update your script tags to use an html import instead wrapping a script, such as the one we are currently providing, this the polyfill will resolve duplicates and only load your script once that way.
