### ISSUE TITLE
Support for Polymer 2

### ISSUE THREAD

**Issue by tirithen** [bendavis78/paper-date-picker#177]
With Polymer 2 being a release candidate it would be nice to port this component. Are there any plans for this?

**Comment by web-padawan** [comment]
I think you should check also this for: https://github.com/the-guide/paper-date-picker
It looks more up-to-date.

**Comment by tirithen** [comment]
Thanks. I'll ask there :)

**Comment by tirithen** [comment]
Ah, that fork did not allow issues, I'll continue looking elsewhere
