### ISSUE TITLE
Uncaught ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by atifwaqar** [bendavis78/paper-date-picker#179]
Hi, 
I get the 3 exceptions/errors in Chrome Console when I import your HTML like this
```html
<link rel="import" href="/sys/paper-date-picker/paper-date-picker.html">
```
![image](https://cloud.githubusercontent.com/assets/4388707/24749508/985eb08c-1ac3-11e7-8813-58f91a7ddf5f.png)

and when I remove the import code my page works fine: 
![image](https://cloud.githubusercontent.com/assets/4388707/24749567/d99376a0-1ac3-11e7-9cab-07862442a51c.png)

Any idea what am I doing wrong here?

**Comment by web-padawan** [comment]
Ensure that [moment-element](https://github.com/bendavis78/moment-element) and corresponding `moment` library are installed in your `sys` directory.

**Comment by atifwaqar** [comment]
@web-padawan 
I have the moment-element. 
![image](https://cloud.githubusercontent.com/assets/4388707/24753800/08cd811c-1ad4-11e7-8254-38497ace33b3.png)

Is there anything else needed?

**Comment by web-padawan** [comment]
As you can see [here](https://github.com/bendavis78/moment-element/blob/master/bower.json#L17), `moment-element` requires moment library as a dependency (in fact, it only provides an HTML import for `moment` which should be also installed). You are missing it, but I have no idea why. Are you copying dependencies manually instead of running `bower install`?

**Comment by atifwaqar** [comment]
Yes, I'm copying dependencies manually. The platform that I'm using, does not allow me to run `bower install` , if I do, it messes a lot of things. :(

**Comment by admwx7** [comment]
All polymer elements rely on a flat peer-dependency structure, which means that if you look at the folder our element sits in then go up one directory you should have a folder at that level named moment-element which as a moment-element.html file within it, which imports based on ../moment/moment.html (another sibling folder under /sys/ for you).

This isn't any sort of issue we can do anything about our on part unfortunately, my recommendation is to fix your build environment, if the above doesn't solve your problem and you're still having issues, just send me an email.
