### ISSUE TITLE
No input value set for forms

### ISSUE THREAD

**Issue by azariah001** [bendavis78/paper-date-picker#181]
The element doesn't contain a hidden input field with a name and value passthrough to allow for use in forms.

**Comment by admwx7** [comment]
This is a limitation of `<form>`, a very unfortunate one, the recommended pattern until they can get browsers to change is to utilize `<iron-form>` I know that's not ideal but it's currently what we are stuck with.  More importantly for browsers that support native shadow dom (most of them now) this won't actually work, this hack only works when using shady dom.

The work-around that would actually solve our problem would be to provide this as a template extension of `<input>` however that support was pushed out by the non-chrome browsers so until a replacement comes along we're just kind of SoL...
