### ISSUE TITLE
When changing date from 31st of any month, it jumps to same day in next month in calendar

### ISSUE THREAD

**Issue by ThilinaTCH** [bendavis78/paper-date-picker#182]
Hi,

I could be able to reproduce this even in Demo in here https://www.webcomponents.org/element/bendavis78/paper-date-picker/demo/demo/index.html.
First set a date to 31st in any month. 
Ex: 31st of May 2017
Then change it to any other date in very next month
Ex: Try to set 5th of June 2017

It will automatically set to 5th of July 2017 instead.

**Comment by psquared2** [comment]
My workaround to this was to repeat a statement under paper-calendar.html, _tapDay function:

```
var item = event.model.item; //for example, we select June 5th
var newDate = new Date(this.date.getTime()); //the current date is May 31st
newDate.setYear(item.year);
newDate.setMonth(item.month); //after this statement, newDate suddenly becomes July
newDate.setMonth(item.month); //after this statement, newDate returns to June
newDate.setDate(item.day);
this.date = newDate;
```

**Comment by admwx7** [comment]
This was addressed in another PR already.
