### ISSUE TITLE
Polymer 2.0 support

### ISSUE THREAD

**Issue by ThilinaTCH** [bendavis78/paper-date-picker#184]
@bendavis78 Is this in road map? If so any estimated date please..

**Comment by loopingz** [comment]
I did a PR there : https://github.com/bendavis78/paper-date-picker/pull/192

**Comment by varletconst** [comment]
I am planning to use this component in a full Polymer 2.x project, therefore started upgrading the component to Polymer 2.x. Could you please create a branch so I can push my code.

Thanks for your help.

**Comment by admwx7** [comment]
You won't be able to push directly to this repo @varletconst just create a branch on your fork and pull request against master on this repo, I can redirect merges after that point.

**Comment by varletconst** [comment]
Well if you had created the branch, I would have made a pull request against that branch...
Anyway, will create the branch on my side.

**Comment by loopingz** [comment]
@varletconst you should look at the PR #192 before i think no need to double work on it

**Comment by admwx7** [comment]
We now have a 2.0-preview branch created, feel free to test against it @varletconst and @loopingz if you notice any issues PR against that branch, once we've had some time to test that it's fully stable I'll merge it into master and release as v2.0.0, in the meantime I'm going to create a v2.0.0-rc1 tag for people to start checking out.

**Comment by loopingz** [comment]
Ok thanks, i m running my fork in production, but I ll revert back to your version next release cycle

**Comment by admwx7** [comment]
Sounds good @loopingz if you need any other changes feel free to post an issue or create a PR, you can always ping me on the polymer slack as well under the name amurdock.

**Comment by rwestlund** [comment]
I've been using the 2.0-preview branch in production for several months now.  Time to make it official?

**Comment by admwx7** [comment]
@rwestlund you're right, kind of let other things distract me, went ahead and merged and created the 2.0.0 tag.
