### ISSUE TITLE
paper-date-picker hides iron-icons

### ISSUE THREAD

**Issue by amanshu-kataria** [bendavis78/paper-date-picker#188]
I used iron-icons in my app written in Polymer 2, but when I imported paper-date-picker the iron-icons disappeared. By inspecting I came to know that the icons are still at their respective positions but are hidden. I guess this has something to do with the paper-date-picker's compatibility issues with Polymer 2.

**Comment by amanshu-kataria** [comment]
@bendavis78 need help please.

**Comment by admwx7** [comment]
Sorry @amanshu-kataria but we are still in the process of porting this element over to 2.0, hope to be wrapping that up shortly, if it's still an issue after that point, feel free to open a new issue.  Keep an eye on #192 in the meantime.

**Comment by amanshu-kataria** [comment]
Are you trying to make it hybrid or just compatible with 2.0?
________________________________

**Comment by admwx7** [comment]
I was planning on going hybrid originally however I think I'm just going to jump it straight to 2. If you want to run hybrid on your element you can resolve to ^1.0 || ^2.0 against this element.

**Comment by amanshu-kataria** [comment]
I was trying to make it compatible with 2.0 but faced some issues as I mentioned earlier. Should I send a PR? It would also save your time as well. :)



________________________________

**Comment by admwx7** [comment]
There's a PR out already that's working and just needs some fixes. Hope to get it merged in the next day or two and a pre-release out.

**Comment by amanshu-kataria** [comment]
Cool. Looking forward towards 2.0 (:
________________________________
