### ISSUE TITLE
Wrong styles when the calendar is hidden

### ISSUE THREAD

**Issue by felixzapata** [bendavis78/paper-date-picker#193]
hi, when you hide the calendar (with `display:none` for example) and you use a button to show it, the styles are wrong calculated. It is look like the width for the days are not the correct.

**Comment by admwx7** [comment]
This is actually a bug I've encountered in quite a few elements, it's due to how iron-resizable-behavior handles the resizing functionality.  Try calling `notifyResize()` on your element once you've toggled it to visible @felixzapata.

**Comment by felixzapata** [comment]
Thanks. It works calling to the `notifyResize()`. 

Another option that can be valid depending on the project is to hide the element with a class like `sr-only`.
