### ISSUE TITLE
When changing year, the display date is not updated

### ISSUE THREAD

**Issue by gwesio** [bendavis78/paper-date-picker#2]
I have noticed ```selectedYearChanged``` does not set ```this.value``` and the selected date component does not update to reflect new values. You do set this in ```selectedDateChanged``` however so I am assuming that should also follow similar process. By the way, I have also noticed the day can sometimes change when selecting year.

**Comment by bendavis78** [comment]
This appears to have been fixed in both v0.1 and v1.0 branches.
