### ISSUE TITLE
Month picker

### ISSUE THREAD

**Issue by zukkun** [bendavis78/paper-date-picker#20]
I want month-picker. Do you plan to it make?

It is like this.
http://demos.telerik.com/kendo-ui/datepicker/index

Thank you.

**Comment by bendavis78** [comment]
The purpose of this element is to follow the material design spec as closely as possible (while borrowing hints from the android implementation). The material design spec doesn't have any kind of month selector UI that I'm aware of.

**Comment by Zecat** [comment]
I think this issue should be reopened, it's very inconvenient to have to change month one by one. It's a missing feature from spec, we should take the lead and implement it until the spec are updated. Moreover, the way to do seems natural, as _gesture already check if the user is dragging vertically or horizontally, drag down could open the month picker.
