### ISSUE TITLE
paper-dialog styles are not applied using the 2.0 preview

### ISSUE THREAD

**Issue by dejan9393** [bendavis78/paper-date-picker#200]
The paper-dialog styles are not being correctly applied when adding the `paper-date-picker-dialog` class to a dialog element.

This is because the `paper-date-picker-dialog-style` file is using the old `<style is="custom-style">...` syntax

**Comment by bendavis78** [comment]
I've created a branch for polymer2.0. See #202

**Comment by bendavis78** [comment]
I've applied the fix to the 2.0-preview branch.
