### ISSUE TITLE
vertical stacking with other controls in a dialog

### ISSUE THREAD

**Issue by gedw99** [bendavis78/paper-date-picker#22]
All works well, except that i need to use it in a dialog with other controls, and i dont want vertical scrolling.
The data picker has its own scrolling, and the whole section should not also scroll.
Maybe i need to learn more polymer styling :)

 <template>
    <style include="shared-styles"></style>

    <section>

    
      <paper-button class="btn" on-tap="showdialog" raised>Change Date</paper-button>

      <paper-dialog id="dialog" modal class="paper-date-picker-dialog" >
        <h3>Age Verification</h3>
        <p>Please select your age</p>
        <paper-date-picker id="picker" responsive-width="655px"></paper-date-picker>
        <div class="buttons">
          <paper-button dialog-dismiss>Cancel</paper-button>
          <paper-button dialog-confirm autofocus>Confirm</paper-button>
        </div>
      </paper-dialog>
    </section>
  </template>

**Comment by gedw99** [comment]
screenshot of the problem.

![datapicker](https://cloud.githubusercontent.com/assets/155690/9991236/ad09be76-6068-11e5-9441-c344e917dc4c.gif)

**Comment by bendavis78** [comment]
The `paper-datepicker-dialog` class is intended to give the styling shown in the material design spec for picker dialogs (these do not include a header). If you're wanting to do any customization beyond that you'll need to do that in your own CSS.  Try just removing that class from the dialog and see if that meets your needs. If not, you can copy the code for that class into your own custom class.
