### ISSUE TITLE
[min|max]-date does nothing

### ISSUE THREAD

**Issue by austinjlaverty** [bendavis78/paper-date-picker#24]
Demo does not demonstrate `min-date`, `max-date`, `minDate` or `maxDate` working.

Very easy to recreate, just try to use any of the above attributes.

I'm currently under a time constraint so I wasn't able to debug as deep as I normally would have liked, so I apologize for the shallow analysis. My initial breakpoints indicated the values are always `null`.

**Comment by alonhar** [comment]
In the paper-calendar

         /* TODO: figure out a user-friendly way to auto-populate years
         * It takes more time on mobile, so there should be some indication that a
         * year is loading. One idea is to make it so that when the user scrolls to
         * the bottom, an indicator appears showing that the content for that year is
         * loading. We'd need extra logic to handle scrolling and removal of years
         * that are hidden from view.
        loadMoreUpper: function() {
        },
        loadMoreLower: function() {
        }
        */

If you want to support maxDate and show another year you can fix this by add loop on the year

replace the populate function from the paper-calendar with this.

     populate: function(currYear, minDate, maxDate) {
      var months = [];
      var month, weeks, day, d, dayInfo, monthData, date = new Date();

      var minYear, maxYear;
      if (maxDate) {
          maxYear = maxDate.getFullYear();
      } else {
          maxYear = currYear;
      }
      if (minYear) {
          minYear = minDate.getFullYear();
      } else {
          minYear = currYear
      }

      for (var year = minYear; year <= maxYear; year++) {
          date.setYear(year);
          date.setHours(0, 0, 0, 0);

          var startMonth = 0;
          var endMonth = 12;
          if (minDate && year === minDate.getFullYear()) {
              startMonth = minDate.getMonth();
          }
          if (maxDate && year === maxDate.getFullYear()) {
              endMonth = maxDate.getMonth() + 1;
              console.log()
          }

          for (month = startMonth; month < endMonth; month++) {
              weeks = [
                  []
              ];
              day = 1;
              date.setMonth(month);
              date.setDate(1);

              // add "padding" days
              for (d = 0; d < date.getDay(); d++) {
                  weeks[0].push({
                      day: null
                  });
              }

              // add actual days
              while (date.getMonth() === month) {
                  if (d % 7 === 0) {
                      // start new week
                      weeks.push([]);
                  }
                  dayInfo = {
                      date: new Date(year, month, day),
                      name: this.isoFormat(year, month, day),
                      year: year,
                      month: month,
                      day: day,
                  };
                  weeks[weeks.length - 1].push(dayInfo);
                  date.setDate(++day);
                  d++;
              }
              monthData = {
                  year: year,
                  month: month,
                  weeks: weeks,
                  domReady: false
              };
              months.push(monthData);
          }
      }
      this.set('_months', months);
  }

**Comment by Bodhiz** [comment]
I've also reproduced the issue with those attributes.

**Comment by bendavis78** [comment]
Fixed in 1.1.0
