### ISSUE TITLE
paper-calendar not displaying at all in IE 11

### ISSUE THREAD

**Issue by L-u-k-e** [bendavis78/paper-date-picker#29]
If you look at the demo in IE 11, you will see that the `paper-calendar` element does not display at all

**Comment by L-u-k-e** [comment]
This issue is caused by a syntax error (or at least I think it's a syntax error) in the declaration of the `_computeYear()` function inside the `paper-calendar` element.  

Right now it looks like this:
  
    _computeYear(initialDate, minDate, maxDate) {
      ...
    }

But its a property being declared on the object literal passed to the `Polymer()` function, so it should be:
    _computeYear: function (initialDate, minDate, maxDate) {
      ...
    }
 
IE complains about the missing ':' and doesn't render the element, but strangely, Chrome just silently ignores it and render the element without an issue.

**Comment by L-u-k-e** [comment]
I went to submit a pull request, but it looks like someone beat me to it:  https://github.com/bendavis78/paper-date-picker/pull/26

Apparently this si an issue in Safari as well. The pull request has no description, but its titled *Fixes the problem Safari*  and the only difference between that branch and master is the syntax change I noted above. 

So, it should probably be pulled.

**Comment by bendavis78** [comment]
I've merged the PR. Apologies for the goof-up!
