### ISSUE TITLE
dynamic locale change impossible

### ISSUE THREAD

**Issue by jahglow** [bendavis78/paper-date-picker#34]
One can't change locale of the calendar dynamically or compute it while creating datepicker even onCreate. If the locale is a computed parameter, the calendar opens always in english locale and the computed locale is applied only when a person selects a date and ONLY to the left/top part displaying the selected date but not to the weekdays/months in the calendar. Only if the person hardcodes the locale of the calendar, only then it's displayed corectly. Could you please make it availiable dynamically?

**Comment by wonsikin** [comment]
+1

**Comment by bendavis78** [comment]
Fixed in 1.1.0
