### ISSUE TITLE
New 1.1.0 version not working

### ISSUE THREAD

**Issue by kungufli** [bendavis78/paper-date-picker#37]
The new 1.1.0 version is not working for me, I get an `Uncaught TypeError: Cannot read property 'apply' of undefined` error at `paper-date-picker.html:326` in Chrome.

**Comment by manfield** [comment]
I've some issue too: Uncaught TypeError: Cannot read property 'getTime' of null we did not have before. It causes some issues at the application. I will dig more to find why it happens.
Reading change logs, no of the changes should affect our app...let's see.

**Comment by kungufli** [comment]
@bendavis78 sorry, it's working fine now, probably I had some other not updated component that was causing the error. Thanks for your help and your great work.
I'm closing this issue since it's not happening anymore for me, @manfield try to execute a `bower update` on your project, if the problem persist you can open a new issue specific for your error.
