### ISSUE TITLE
locale attribute does not appear to work

### ISSUE THREAD

**Issue by Praneesh** [bendavis78/paper-date-picker#4]
Even though my PCs locale is en-US, I am unfortunately seeing the time only in Chineese. I have tried changing the locale "en-US" during initialization but of no luck. I tried to play around the other attributes but with not much success.

This is a modified snippet from the demo code available on the site.

```
<paper-date-picker locale='en-US' maxYear='2017' date='2014-04-20' id="picker"></paper-date-picker>

```
Screenshot FYR.

![locale](https://cloud.githubusercontent.com/assets/941176/7807452/69d7e6c6-03a9-11e5-8adb-035f9cebe88c.png)

Please help.

**Comment by bendavis78** [comment]
That's very odd, my system is configured en-US as well and I'm not seeing chinese. My guess is that you have a locale setting elsewhere that's being detected by [momentjs](http://momentjs.com/docs/#/i18n/). Either that or some extension you have is causing issues.

**Comment by bendavis78** [comment]
Closing for now. Feel free to re-open is your cam provide steps to reproduce.
