### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMonth' of undefined

### ISSUE THREAD

**Issue by agozie** [bendavis78/paper-date-picker#42]
This happens upon start up if I vulcanize/crisper my app, otherwise it works fine. Version 1.1.2.
Edit:
It demo works but it does not work in my app, even without vulcanization.

**Comment by bendavis78** [comment]
Can you provide some code or an example I can use to reproduce the issue?

**Comment by bendavis78** [comment]
Closing for lack of response

**Comment by Ankita-J** [comment]
I have same error in my project too.  Has anybody solution for it? Please help.
