### ISSUE TITLE
After vulcanization Uncaught TypeError: Cannot read property '_week' of null

### ISSUE THREAD

**Issue by Bodhiz** [bendavis78/paper-date-picker#47]
After vulcanization I retrieve the following error in console : Uncaught TypeError: Cannot read property '_week' of null. 
That comes from the _localeChanged method : 

![image](https://cloud.githubusercontent.com/assets/2632229/11767600/c6b6da20-a1b3-11e5-805f-59093b31b69e.png)

**Comment by bendavis78** [comment]
Does this happen when using master? If so, can you post some code that shows your usage of the element? I'm unable to reproduce.
