### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by fadfood** [bendavis78/paper-date-picker#49]
RTL used to be working and when I updated to 1.1.2 it is missy

**Comment by bendavis78** [comment]
Hi, please provide an example of how to repoduce using plunker, jsbin, jsfiddle, etc. You can use the following plunker as a starting point: http://plnkr.co/edit/9c787GHiBzX7zI5x6gsX

**Comment by bendavis78** [comment]
Closing after no response. Feel free to re-submit if this is still an issue.

**Comment by bendavis78** [comment]
Closing due to no response. Feel free to re-open with reproducible example.
