### ISSUE TITLE
Upgrade to polymer 1.0

### ISSUE THREAD

**Issue by mahadazad** [bendavis78/paper-date-picker#5]

**Comment by rkstar** [comment]
please!  absolutely.  this is a very good datepicker.

**Comment by bendavis78** [comment]
I've started work on a `polymer1` branch. It's not entirely complete, dates still aren't selectable and theming needs to be implemented. Pull requests are welcomed!

**Comment by bendavis78** [comment]
paper-date-picker 1.0.0 is now released :-)

**Comment by rkstar** [comment]
excellent! thank you!
