### ISSUE TITLE
Calendar populated thrice the first time

### ISSUE THREAD

**Issue by Zecat** [bendavis78/paper-date-picker#52]
Try put the following in [_populate](https://github.com/bendavis78/paper-date-picker/blob/master/paper-calendar.html#L307) function

``` js
console.log("currentYear: "+currentYear);
console.log("currentMonth: "+currentMonth);
console.log("---------");
```

reload, the console gives you

```
currentYear: 2015
currentMonth: 12
---------
currentYear: 2017
currentMonth: 12
---------
currentYear: 2017
currentMonth: 4
---------
```

Critical performance issue !

**Comment by admwx7** [comment]
This was handled as part of the 1.1.5 release and relies on usage of the async functionality, I'll need to revamp how this works as part of the transition to 2.0.0 but closing for now.
