### ISSUE TITLE
select 2 dates

### ISSUE THREAD

**Issue by Bodhiz** [bendavis78/paper-date-picker#65]
It would be a great improvement to add a range option to allow select 2 dates in the same date-picker like Airbnb does.

**Comment by Zecat** [comment]
:+1: 
But there will be a conflict with month swipe. Needs something like a delay after the first day has been selected for the track handler to know if we want to swipe or to select an interval. Or the first taped day selects the starting date and second tape selects the end date. What do you think?

**Comment by Bodhiz** [comment]
I would say that the first taped day select the starting date and the second tape selects the end date. We should also highlight with the accent color all the dates in the range. 
Ryanair.com datepicker is also a very good example.

**Comment by ronnyroeller** [comment]
+1

**Comment by bendavis78** [comment]
This might fall out of the scope in terms of the MD spec, but I wouldn't be against adding a single `endDate` attribute that, when set, highlights all dates between `date` and `endDate`.

**Comment by Bodhiz** [comment]
I can't believe that all the travel companies offers a range select datepicker if it was not efficient. In my opinion this use case is just a lack in the MD specs.

**Comment by jahglow** [comment]
+100, this is a must, really rather than having two date pickers, having
one is better

чт, 10 марта 2016, 16:14 Jonathan <notifications@github.com>:

**Comment by web-padawan** [comment]
Selecting date range is quite useful thing. This is implemented by [edk-date-picker](https://github.com/Turksat/edk-date-picker) which is a bit outdated.

I'm going to create a PR to implement it here, but this would require to change component's output (to be able to produce two dates). 
Shall I add an extra `range` property or just use an existing `date` ?
@bendavis78 WDYT?

**Comment by bendavis78** [comment]
Moving discussion to #124
