### ISSUE TITLE
Layout breaks when paper-dialog has entry-animation

### ISSUE THREAD

**Issue by diegohaz** [bendavis78/paper-date-picker#66]
Adding any `entry-animation` to `paper-dialog` makes `paper-date-picker` layout to break at the first rendering.

<img width="723" alt="screen shot 2015-12-30 at 16 53 18" src="https://cloud.githubusercontent.com/assets/3068563/12055638/4350e0a2-af16-11e5-8693-9a15ec562734.png">

Reference: https://github.com/Collaborne/paper-date-picker-item/issues/5

**Comment by ronnyroeller** [comment]
+1

**Comment by ifaris7** [comment]
There is a private method on the component named '_resizeHandler', call it when the animation finish and it should fix it.

**Comment by bendavis78** [comment]
Dup of #43.
