### ISSUE TITLE
app breaks when I try to import paper-date-picker

### ISSUE THREAD

**Issue by radupopa2010** [bendavis78/paper-date-picker#67]
Hi,

My app breaks when I try to import paper-date-picker
this is how I try to import it:

 <  link rel="import" href="bower_components/paper-date-picker-master/paper-date-picker.html"   >

The app seems to enter in an infinite loop and the it breaks after a while ... 

any ideas ?

**Comment by Typel** [comment]
This is not an official Polymer element, so it isn't necessarily packaged the same way. One quick look at the source code reveals that there are several external requirements which are not included with this file repository.

First of all, the component expects to be placed in its own folder within the same folder as your other elements (such as your _/bower_components_ folder). 

Other elements it expects to have as neighbors:

- /polymer/polymer.html
- /iron-media-query/iron-media-query.html
- /neon-animation/neon-animated-pages.html
- /neon-animation/neon-animatable.html
- /neon-animation/animations/fade-in-animation.html
- /neon-animation/animations/fade-out-animation.html
- /iron-resizable-behavior/iron-resizable-behavior.html
- /iron-selector/iron-selector.html
- /iron-flex-layout/iron-flex-layout.html
- /paper-button/paper-button.html
- /paper-styles/paper-styles.html

Additionally, it requires `moment-element` to be present, which is another 3rd party element written by the same author and available here: https://github.com/bendavis78/moment-element

`moment-element` also has its own requirements not included. It requires the moment.js library. By default, `moment-element` looks to find files in these locations relative to where it lives on the server:

- ../moment/min/moment.js
- ../moment/min/moment-with-locales.js

I just placed mine elsewhere and changed the links in `moment-import.html` and `moment-with-locales-import.html`

**Comment by onepartninja** [comment]
This helped me - I had everything except the actual moment lib. Thanks a lot

**Comment by bendavis78** [comment]
Polymer elements are typically managed using Bower. As long as you include this repository in your bower.json file, all dependencies should be automatically pulled in for you. Read more about using elements here: https://elements.polymer-project.org/guides/using-elements
