### ISSUE TITLE
datePicker choose year problem

### ISSUE THREAD

**Issue by khoanguyenlio** [bendavis78/paper-date-picker#68]
When you extend range of the year to choose like 1950-current year. You will get a problem like this
![bugdatepicker](https://cloud.githubusercontent.com/assets/9152575/12112095/d172cafc-b3cc-11e5-812b-c7863695fb59.jpg)
You can add style height: 100%; to iron-list but it's workaround.

**Comment by gertcuykens** [comment]
Master doesn't use iron-list i think but master still doesn't work in chrome
```
      #yearList {
        @apply(--layout-vertical);
        @apply(--layout-center-center);
        display: block;
        height: 100%;
        overflow-y: auto;
        overflow-x: hidden;
      }
```
Please provide workaround for master because I can't figure it out, maybe its polymer bug?

**Comment by khoanguyenlio** [comment]
sorry i mean iron-selector. the problem is scroll-height of <div id="yearList" and <iron-selector id="yearSelector not matching

**Comment by gertcuykens** [comment]
`#yearSelector {height: 100%;}` works in safari and chrome can you make a PR? Hope this will put into master soon.

**Comment by khoanguyenlio** [comment]
Yeah. Maybe, but i'm waiting for @bendavis78 check this issues -_-.

**Comment by bendavis78** [comment]
@Zecat recently contributed a change to convert the year list to a component using iron-list. Can you please update to master and check to see if this is still an issue for you?

**Comment by gertcuykens** [comment]
it seems to work now but the right scrollbar is off center

**Comment by bendavis78** [comment]
Not sure what's causing the scrollbar to be off. It doesn't appear that way on mobile, though, which is odd. I'll add a new bug for that.
