### ISSUE TITLE
Implement form element behavior

### ISSUE THREAD

**Issue by Zecat** [bendavis78/paper-date-picker#70]
&lt;input-date-picker&gt; should implement Polymer.IronFormElementBehvior and 'date' attribute should be rename 'value'. This is the opportunity for a v2 release.

**Comment by bendavis78** [comment]
I don't see date/time pickers as necessarily form input elements, but rather agnostic to how their values are used. Users wanting to implement in a form should need to bind to whatever input element holds the value. Willing to discuss, though.
