### ISSUE TITLE
Don't include all locales

### ISSUE THREAD

**Issue by ankon** [bendavis78/paper-date-picker#74]
Sometimes it is not needed to include all locales of moment.js, and then those extra locales cost quite a bit in download size and parsing time.

It would be nice if the component would only use `moment-element/moment-import.html`, and the callers would be responsible for referencing the extra locales.

We have that implemented on https://github.com/Collaborne/paper-date-picker/tree/improvement/no-locales, but it depends on https://github.com/bendavis78/moment-element/pull/1

What do you think?

**Comment by bendavis78** [comment]
Agreed. Adding bug label to put this into the fix backlog.

**Comment by juk-eluca** [comment]
+1 It would be great to have the possibility to load this component without locales

**Comment by aglusk** [comment]
Would this be the cause of getting out of memory errors, when building a polymer app including this element?

**Comment by tiberioalunni** [comment]
Using paper-date-picker with angular2 locale is no more working.
It is caused by the replace of 
<link rel="import" href="../moment-element/moment-with-locales-import.html">
with
<link rel="import" href="../moment-element/moment-import.html">
in file paper-calendar.html
