### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by mibamur** [bendavis78/paper-date-picker#78]
demo not available

**Comment by khoanguyenlio** [comment]
what do you mean demo is not available? 

http://bendavis78.github.io/paper-date-picker/paper-date-picker/demo/

**Comment by mibamur** [comment]
There are no demo link on component page.

https://github.com/bendavis78/paper-date-picker/pull/79

**Comment by khoanguyenlio** [comment]
Ok you can close this issue :dancer:

**Comment by Link2Twenty** [comment]
I've submitted a pull request to fix this.

**Comment by bendavis78** [comment]
fixed in previous commit.
