### ISSUE TITLE
Infinite recursion when setting the date.

### ISSUE THREAD

**Issue by shaun-blake** [bendavis78/paper-date-picker#81]
I am getting what looks like infinite recursion when setting the date. In the console there are many lines of:
`Uncaught RangeError: Maximum call stack size exceeded.`

It might be related to this (the _dateChanged function gets called many times):
https://github.com/bendavis78/paper-date-picker/blob/master/paper-calendar.html#L585

Here's a Plunker to demonstrate:
http://plnkr.co/edit/zqytBCZa6jvShKupUb4g

Just open the console and run the plunker. You should see the errors.

**Comment by jerryf196** [comment]
Getting the same issue

**Comment by gertcuykens** [comment]
remove observer: '_dateChanged' completely for a quick fix, i think in most cases you don't need it anyway.

**Comment by nicolasFauren** [comment]
Does anyone still have this issue in 1.1.4?

**Comment by faan11** [comment]
same problem to me but  i resolve in this way:
```
  if (!this._withinValidRange(date)) {
          console.warn('Date outside of valid range: ' + date);
          //this.date = date = oldValue;
          this.date = this.minDate; // some problem who cares ...
 }
```
