### ISSUE TITLE
Naming for this project

### ISSUE THREAD

**Issue by matfin** [bendavis78/paper-date-picker#95]
Hi,

Just a suggestion - you should update the heading in the README for this project to reference the bower component name correctly. 

I ended up installing a completely different module with a similar idea [git://github.com/David-Mulder/paper-date-picker.git](paper-date-picker) thinking it was yours.

**Comment by nicholaswmin** [comment]
+ 1

**Comment by bendavis78** [comment]
I've added a note in the README.
