### ISSUE TITLE
Dialog style breaks when nested in another element.

### ISSUE THREAD

**Issue by curtiscovington** [bendavis78/paper-date-picker#97]
I was attempting to create a paper-date-picker-input element and noticed that the style breaks if the dialog is included as part of another element.

**Comment by bendavis78** [comment]
Hi, can you provide an example? You can use this plunkr as a starting point: http://plnkr.co/edit/9c787GHiBzX7zI5x6gsX

**Comment by bendavis78** [comment]
Closing due to no-response. Feel free to re-open if you're able to provide steps to reproduce.
