### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rubenstolk** [bendavis78/paper-date-picker#99]
In the demo when calling:

```js
Polymer.dom(document).querySelector('#scope').set('date', new Date())
```

Something goes wrong wrt databinding and Polymer throws `Maximum call stack size exceeded `

**Comment by rubenstolk** [comment]
I think this is due to the fact that `date` has an observer `_dateChanged` which again calls `this.set('date', ...);`

**Comment by rubenstolk** [comment]
Ah I guess this was already taken care of in https://github.com/bendavis78/paper-date-picker/pull/96/files

**Comment by markstewie** [comment]
Was this fixed? Having the same problem... `bower update` is not pulling this change to fix the problem.

**Comment by rubenstolk** [comment]
The PR solves this indeed

**Comment by markstewie** [comment]
I see.. pull request hasn't been merged yet... will have to roll back until it has.

**Comment by rubenstolk** [comment]
Yeah I really hope @bendavis78 will look into some urgent issues and pending PR's soon. In the meanwhile this is how I got it done using `bower.json`:

```json
    "paper-date-picker": "git@github.com:matfin/paper-date-picker.git#master",
```

**Comment by markstewie** [comment]
Agreed... 
I just rolled back using `bower install https://github.com/bendavis78/paper-date-picker.git#1.1.2 --save` which is working.

**Comment by bendavis78** [comment]
Dup of #81
